loinc:
  release:
    default: '2.67'
    '2.67':
      version: '2.78'
      path: 'loinc_release/2.67' # runtime home directory-relative path
    '2.78':
      version:  '2.78'
      path: 'loinc_release/Loinc_2.78'

loinc_tree:
  release:
    default: '2.78'
    '2.78':
      tree_path: 'loinc_trees/2024-08-31'


snomed:
  release:
    default: 'INT_20240801'
    INT_20240801:
      files:
        description: 'snomed_release/SnomedCT_InternationalRF2_PRODUCTION_20240801T120000Z/Snapshot/Terminology/sct2_Description_Snapshot-en_INT_20240801.txt'
        relationship: 'snomed_release/SnomedCT_InternationalRF2_PRODUCTION_20240801T120000Z/Snapshot/Terminology/sct2_Relationship_Snapshot_INT_20240801.txt'

loinc_snomed:
  release:
    default: '20231015'
    '20231015':
      files:
        description: 'loinc_snomed_release/Snapshot/Terminology/xsct2_Description_Snapshot-en_LO1010000_20231015.txt'
        identifier: 'loinc_snomed_release/Snapshot/Terminology/xsct2_Identifier_Snapshot_LO1010000_20231015.txt'
        relationship: 'loinc_snomed_release/Snapshot/Terminology/xsct2_Relationship_Snapshot_LO1010000_20231015.txt'
        part_mapping: 'loinc_snomed_release/part-mappings_0.0.3.tsv'

logging:
  formatters:
    default:
      format: '%(asctime)s %(levelname)-8s %(name)-15s %(message)s'
      datefmt: '%Y-%m-%d %H:%M:%S'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: default
      level: DEBUG
#      filters: [ allow_foo ]
      stream: ext://sys.stdout
#    file:
#      class: logging.handlers.RotatingFileHandler
#      formatter: precise
#      filename: logconfig.log
#      maxBytes: 1024
#      backupCount: 3
  disable_existing_loggers: False
  loggers:
    '':
      level: WARN
      handlers: [console]
#    cli_runtime:
#      handlers: [console]
#      level: INFO
#      propagate: False
  version: 1