[tool.poetry]
name = "comp-loinc"
version = "0.1.0"
description = "Computable OWL Formalization of LOINC"
authors = ["Tim  Putman <putmantime@users.noreply.github.com>"]
readme = "README.md"

packages = [
    {include = "comp_loinc",  from = "src"},
    {include = "loinclib",  from = "src"}
]

[tool.poetry.scripts]
#comp-loinc = 'comp_loinc:cli.cli'
comploinc = 'comp_loinc.cli:comploinc_cli'
comploinc-file = 'comp_loinc.cli:comploinc_file_cli'

[tool.poetry.dependencies]
python = "^3.11"
linkml = "^1.5.0"
linkml-owl = "^0.2.7"
typer = "^0.9.0"
pandas = "^2.0.0"
sssom = "^0.3.26"
networkx = "^3.1"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
